import re
from typing import Dict

def parse_log_calypso(log: str, test_spec: "TestSpec") -> Dict[str, str]:
    """
    Parser for test logs generated by Calypso test suite.

    The function scans the log for lines that contain a test name followed by a
    status word (passed, failed, skipped, error, timeout).  It returns a
    dictionary mapping each test name to its status in uppercase.

    Parameters
    ----------
    log : str
        The raw log text produced by Calypso.
    test_spec : TestSpec
        An object that may contain a ``tests`` attribute listing the tests
        that should be considered.  If the attribute is missing or empty,
        all discovered tests are returned.

    Returns
    -------
    dict[str, str]
        Mapping from test name to status.
    """
    # Regular expression that captures a test name and a status word.
    # Example matches: "Test foo passed", "Test bar failed", etc.
    test_line_re = re.compile(
        r"Test\s+(\S+)\s+(passed|failed|skipped|error|timeout)",
        re.IGNORECASE,
    )

    # Collect all discovered tests.
    discovered: Dict[str, str] = {}
    for line in log.splitlines():
        match = test_line_re.search(line)
        if match:
            name, status = match.group(1), match.group(2).upper()
            discovered[name] = status

    # If the test_spec provides a list of tests to keep, filter the results.
    tests_to_keep = getattr(test_spec, "tests", None)
    if tests_to_keep:
        # Ensure the list is a set for fast lookup.
        keep_set = set(tests_to_keep)
        filtered = {name: status for name, status in discovered.items() if name in keep_set}
        return filtered

    return discovered