import json
import os
import random
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

import click
import typer
import yaml
from tqdm import tqdm

# Assume these are defined elsewhere in the package
try:
    from .config import (
        Backend,
        TASK_NAMES_TO_YAML,
        SAMPLING_PARAMS_DEFAULT,
        get_system_prompt_keys,
    )
except Exception:
    # Minimal stubs for standalone usage
    class Backend(str):
        VLLM = "vllm"
        OPENAI = "openai"

    TASK_NAMES_TO_YAML = {"example": "example.yaml"}
    SAMPLING_PARAMS_DEFAULT = "{}"
    def get_system_prompt_keys() -> List[str]:
        return []

# --------------------------------------------------------------------------- #
# Helper functions
# --------------------------------------------------------------------------- #

def _load_yaml(path: str) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)

def _parse_json_str(s: str) -> Dict[str, Any]:
    try:
        return json.loads(s) if s else {}
    except json.JSONDecodeError as e:
        raise typer.BadParameter(f"Invalid JSON: {e}") from e

def _ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)

def _get_system_prompt(
    name: Optional[str], custom: Optional[str]
) -> Optional[str]:
    if custom:
        return custom
    if name:
        # In real implementation, load from a registry
        return f"System prompt for {name}"
    return None

def _prepare_prompt(
    system_prompt: Optional[str],
    user_prompt: str,
    assistant_prefill: Optional[str],
) -> str:
    parts = []
    if system_prompt:
        parts.append(system_prompt)
    parts.append(user_prompt)
    if assistant_prefill:
        parts.append(assistant_prefill)
    return "\n".join(parts)

def _run_inference(
    backend: Backend,
    model: str,
    prompt: str,
    sampling_params: Dict[str, Any],
    backend_args: Dict[str, Any],
    batch_size: int,
) -> str:
    """
    Placeholder inference function. In a real implementation this would
    dispatch to the chosen backend (e.g., vllm, openai, etc.).
    """
    # For demonstration, just echo the prompt with a dummy suffix
    return f"{prompt}\n[Generated by {backend.value} model {model}]"

def _save_result(
    result_dir: Path,
    task: str,
    sample_id: int,
    prompt: str,
    response: str,
    overwrite: bool,
) -> None:
    out_path = result_dir / f"{task}_sample_{sample_id}.jsonl"
    if out_path.exists() and not overwrite:
        return
    data = {"prompt": prompt, "response": response}
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(data, f)
        f.write("\n")

# --------------------------------------------------------------------------- #
# Main evaluate function
# --------------------------------------------------------------------------- #

def evaluate(
    ctx: typer.Context,
    task: Annotated[
        str,
        typer.Option(
            ...,
            help="Task to process.",
            click_type=click.Choice(list(TASK_NAMES_TO_YAML.keys())),
            case_sensitive=False,
        ),
    ],
    model: Annotated[str, typer.Option(..., help="The model to run")],
    backend: Annotated[
        Backend,
        typer.Option(
            help="Backend to use for inference.",
            case_sensitive=False,
        ),
    ] = Backend.VLLM,
    backend_args: Annotated[
        str,
        typer.Option(
            help="Backend parameters to use for inference.",
            case_sensitive=False,
        ),
    ] = "",
    sampling_params: Annotated[
        str,
        typer.Option(
            help="Sampling parameters to use for inference.",
            case_sensitive=False,
        ),
    ] = SAMPLING_PARAMS_DEFAULT,
    result_dir: Annotated[
        str,
        typer.Option(
            help="Result directory to save outputs.",
        ),
    ] = "./",
    system_prompt_name: Annotated[
        str,
        typer.Option(
            help="System prompt template to use, overriding any pre-configured system prompt for this model.",
            click_type=click.Choice(get_system_prompt_keys()),
        ),
    ] = None,
    system_prompt: Annotated[
        str,
        typer.Option(
            help="System prompt to use, overriding any pre-configured system prompt for this model."
        ),
    ] = None,
    n: Annotated[
        int, typer.Option(help="Number of samples generated per problem.")
    ] = None,
    seed: Annotated[int, typer.Option(help="Random seed.")] = 41,
    assistant_prefill: Annotated[
        str,
        typer.Option(
            help=r'Assistant prefill for the model response, overriding any pre-configured assistant prefill for this model. Ex: "<think>\n"'
        ),
    ] = None,
    as_test: Annotated[
        bool, typer.Option(help="Perform a test run on 10 samples of the dataset.")
    ] = False,
    overwrite: Annotated[
        bool, typer.Option(help="Overwrite existing results.")
    ] = False,
    batch_size: Annotated[
        int,
        typer.Option(
            help="Batch size for inference. only applicable for the vllm backend."
        ),
    ] = 64,
):
    """
    Evaluate a model on a specified task using the chosen backend.
    """
    # Resolve paths and parameters
    task_yaml_path = TASK_NAMES_TO_YAML.get(task)
    if not task_yaml_path:
        raise typer.BadParameter(f"Unknown task: {task}")

    dataset = _load_yaml(task_yaml_path)
    prompts: List[str] = dataset.get("prompts", [])
    if not prompts:
        raise typer.BadParameter(f"No prompts found in {task_yaml_path}")

    # Override system prompt if provided
    sys_prompt = _get_system_prompt(system_prompt_name, system_prompt)

    # Parse backend and sampling arguments
    backend_args_dict = _parse_json_str(backend_args)
    sampling_params_dict = _parse_json_str(sampling_params)

    # Prepare result directory
    result_path = Path(result_dir).expanduser().resolve()
    _ensure_dir(result_path)

    # Set random seed
    random.seed(seed)

    # Determine number of samples per prompt
    samples_per_prompt = n if n is not None else 1

    # If test mode, limit to 10 prompts
    if as_test:
        prompts = prompts[:10]

    # Main loop
    for idx, prompt in enumerate(tqdm(prompts, desc="Processing prompts")):
        for sample_idx in range(samples_per_prompt):
            full_prompt = _prepare_prompt(
                sys_prompt, prompt, assistant_prefill
            )
            # In a real implementation, batch inference would be used
            response = _run_inference(
                backend=backend,
                model=model,
                prompt=full_prompt,
                sampling_params=sampling_params_dict,
                backend_args=backend_args_dict,
                batch_size=batch_size,
            )
            _save_result(
                result_dir=result_path,
                task=task,
                sample_id=idx * samples_per_prompt + sample_idx,
                prompt=full_prompt,
                response=response,
                overwrite=overwrite,
            )
    typer.echo(f"Results saved to {result_path}")