from typing import List, Tuple

# Try to import the expected CayleyGraphDef. If it is not available,
# define a minimal stub that matches the expected interface.
try:
    from cayley_graph_def import CayleyGraphDef  # type: ignore
except Exception:
    from dataclasses import dataclass

    @dataclass
    class CayleyGraphDef:
        n: int
        generators: List[Tuple[int, ...]]


def signed_reversals(n: int) -> CayleyGraphDef:
    """
    Cayley graph generated by reverses of all possible signed n(n+1)/2 substrings.

    The graph is for S_{2n} (n>=1) representing a graph for n elements, where i-th index
    represents bottom side of i-th element, and (n+i)-th index represents top side of i-th element.
    The graph has n generators denoted R[1..1], R[1..2]..R[n..n], where R[i..j] is signed reverse
    of elements i,i+1..j (or actually indexes i..j, n+i..n+j).
    """
    generators: List[Tuple[int, ...]] = []

    for i in range(1, n + 1):
        for j in range(i, n + 1):
            # Create identity permutation of length 2n
            perm = list(range(2 * n))
            i0 = i - 1
            j0 = j - 1
            # Apply signed reversal on the segment [i0, j0]
            for k in range(i0, j0 + 1):
                # Bottom side index k maps to top side index n + (i0 + j0 - k)
                perm[k] = n + (i0 + j0 - k)
                # Top side index n + k maps to bottom side index (i0 + j0 - k)
                perm[n + k] = (i0 + j0 - k)
            generators.append(tuple(perm))

    return CayleyGraphDef(n, generators)