from typing import List, Tuple

# Assuming CayleyGraphDef is defined elsewhere in the project.
# If not, you can replace it with a simple dataclass or a dictionary.
try:
    from graph_def import CayleyGraphDef  # Adjust import path as needed
except ImportError:
    # Fallback definition for demonstration purposes
    from dataclasses import dataclass

    @dataclass
    class CayleyGraphDef:
        group: str
        generators: List[Tuple[int, ...]]
        name: str = ""

def larx(n: int) -> CayleyGraphDef:
    """
    Cayley graph for S_n (n >= 2), generated by transposition-based permutations.
    Creates two generators: one with 0,1 transposition and one with cyclic shift.
    """
    if n < 2:
        raise ValueError("n must be at least 2")

    # Generator 1: transposition (0,1)
    trans = tuple(1 if i == 0 else 0 if i == 1 else i for i in range(n))

    # Generator 2: cyclic shift (0,1,2,...,n-1)
    shift = tuple((i + 1) % n for i in range(n))

    return CayleyGraphDef(
        group=f"S_{n}",
        generators=[trans, shift],
        name=f"larx_{n}"
    )