def _compute_all_transpositions_cayley_growth(n_str: str) -> list[int]:
    """
    Compute the growth function for the Cayley graph of the symmetric group
    generated by all transpositions.  The growth function gives, for each
    n ≥ 1, the number of permutations of n elements that are at distance
    n‑1 from the identity in this Cayley graph.

    According to OEIS A094638, this number is:
        a(1) = 1
        a(n) = n! / 2   for n ≥ 2

    Parameters
    ----------
    n_str : str
        String representation of the maximum n for which to compute the
        growth values.

    Returns
    -------
    list[int]
        A list of length n where the i‑th element (0‑based) is the growth
        value for n = i+1.
    """
    n = int(n_str)
    if n <= 0:
        return []

    growth = [0] * n
    fact = 1
    for i in range(1, n + 1):
        fact *= i
        if i == 1:
            growth[i - 1] = 1
        else:
            growth[i - 1] = fact // 2
    return growth