from .cayley_graph_def import CayleyGraphDef, MatrixGenerator

def signed_reversals(n: int) -> CayleyGraphDef:
        """Cayley graph generated by reverses of all possible signed n(n+1)/2 substrings.

        Actually is a graph for S_2n (n>=1) representing a graph for n elements, where i-th index represents bottom
        side of i-th element, and (n+i)-th index represents top side of i-th element. The graph has n generators
        denoted R[1..1],R[1..2]..R[n..n], where R[i..j] is signed reverse of elements i,i+1..j
        (or actually indexes i..j,n+i..n+j).
        """
        assert n >= 1
        generators = []
        generator_names = []
        for i in range(n):
            for j in range(i, n):
                perm = []
                perm += list(range(i))
                perm += list(range(n + j, n + i - 1, -1))
                perm += list(range(j + 1, n))
                perm += list(range(n, n + i))
                perm += list(range(j, i - 1, -1))
                perm += list(range(n + j + 1, n + n))
                generators.append(perm)
                generator_names.append(f"R[{i}..{j}]")
        return CayleyGraphDef.create(generators, central_state=list(range(2 * n)), generator_names=generator_names)