import sqlalchemy as sa
import sqlmodel
from alembic import op

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('privacy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prowlarrsource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('indexer_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seeders', sa.Integer(), nullable=False),
    sa.Column('leechers', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('publishDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['indexer_id'], ['indexer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###