import sqlalchemy as sa
from alembic import op
from sqlmodel.sql import sqltypes

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_keys",
        sa.Column("refund_mint_url", sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "api_keys",
        sa.Column("refund_currency", sqltypes.AutoString(), nullable=True),
    )
    op.drop_column("api_keys", "mint_url")
    # ### end Alembic commands ###