from .cayley_graph_def import CayleyGraphDef, MatrixGenerator

def larx(n: int) -> CayleyGraphDef:
        """
        Cayley graph for S_n (n >= 2), generated by transposition-based permutations.
        Creates two generators: one with 0,1 transposition and one with cyclic shift.
        """
        assert n >= 2, "Need n >= 2"
        generators = []
        generator_names = []
        perm1 = [1, 0] + list(range(2, n))
        generators.append(perm1)
        generator_names.append(f"({' '.join(map(str, perm1))})")
        perm2 = [0] + list(range(2, n)) + [1]
        generators.append(perm2)
        generator_names.append(f"({' '.join(map(str, perm2))})")
        name = f"larx-{n}"
        return CayleyGraphDef.create(
            generators, central_state=list(range(n)), generator_names=generator_names, name=name
        )